title: GM-Dev
description: Conception et Développement d'applications informatiques
author: Michel Guillon
show_downloads: false
google_analytics: G-M5FFVQXXYY
theme: jekyll-theme-hacker
timezone: Europe/Paris

paginate: 4
paginate_path: "/blog/page:num/"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-feed]

jekyll_compose:
  post_default_front_matter:
    last_modified_at: 
    permalink: 
    description:
    image:
    published: true
    sitemap: true
    excerpt_separator: <!--more-->
    categories:
    tags:

collections:
  skills:
    output: true
    permalink: /skills/:path/
  projects:
    output: true
    permalink: /projects/:path/

social:
  github: michel-guillon

feed:
  posts_limit: 5
  excerpt_only: true
